name: Setup Kude
description: Setup Kude CLI
inputs:
  version:
    description: Kude version to download
    required: true
runs:
  using: composite
  steps:
    - name: Download
      run: curl -sSL -o /usr/local/bin/kude "https://github.com/arikkfir/kude/releases/download/${{ inputs.version }}/kude-linux-amd64"
      shell: bash
