name: Deployment

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      GCP_BILLING_ACCOUNT_ID:
        required: true
      GCP_PROJECT_ID:
        required: true
      GCP_SA_GHA_ARIKKFIR_DEPLOYMENT_KEY:
        required: true
    outputs:
      plan_outcome:
        value: ${{ jobs.plan-deployment.outputs.plan_outcome }}
      plan_output:
        value: ${{ jobs.plan-deployment.outputs.plan_output }}
      apply_outcome:
        value: ${{ jobs.apply-deployment.outputs.apply_outcome }}
      apply_output:
        value: ${{ jobs.apply-deployment.outputs.apply_output }}

defaults:
  run:
    shell: bash -eu {0}

concurrency:
  cancel-in-progress: false
  group: ${{ inputs.environment }}

jobs:

  plan-deployment:
    name: Plan
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.env.kfirs.com
    defaults:
      run:
        working-directory: infrastructure/cloud
    env:
      TF_IN_AUTOMATION: true
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_gcp_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT_ID }}
      TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_gcp_region: europe-west3
      TF_VAR_gcp_zone: europe-west3-a
    outputs:
      plan_outcome: ${{ steps.plan.outcome }}
      plan_output: ${{ steps.plan.outputs.stdout }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - uses: google-github-actions/auth@v0
        with:
          service_account: gha-arikkfir-deployment@arikkfir.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCP_SA_GHA_ARIKKFIR_DEPLOYMENT_KEY }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - run: terraform init -input=false -no-color
      - run: terraform plan -input=false -lock-timeout=180s -no-color -out tfplan
        id: plan
      - run: tar -cvjf plan.tar.bz2 .terraform .terraform.lock.hcl *.tf tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: infrastructure/cloud/plan.tar.bz2
          if-no-files-found: error
          retention-days: 1

  apply-deployment:
    name: Apply
    needs: plan-deployment
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.env.kfirs.com
    outputs:
      apply_outcome: ${{ steps.apply.outcome }}
      apply_output: ${{ steps.apply.outputs.stdout }}
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account: gha-arikkfir-deployment@arikkfir.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCP_SA_GHA_ARIKKFIR_DEPLOYMENT_KEY }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - uses: actions/download-artifact@v3
        with:
          name: plan
      - run: tar -xvjf plan.tar.bz2
      - run: terraform apply -input=false -lock-timeout=180s -auto-approve -no-color tfplan
        id: apply
        env:
          TF_IN_AUTOMATION: true
          TF_VAR_environment: ${{ inputs.environment }}
          TF_VAR_gcp_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT_ID }}
          TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: europe-west3
          TF_VAR_gcp_zone: europe-west3-a
